<!--
SPDX-FileCopyrightText: 2026 Jason Scheffel <contact@jasonscheffel.com>
SPDX-License-Identifier: AGPL-3.0-or-later
-->

<script lang="ts">
  import ThemeToggle from "../components/ThemeToggle.svelte";

  const liveWords =
    "The sentence you are hearing right now was produced by a machine, and the voice reading it to you is also a machine, which means at no point in this pipeline was a person involved.".split(
      " ",
    );

  const voices = ["kokoro / local", "piper / local", "web speech", "kokoro / gpu", "chatterbox / gpu"];
  const speeds = ["1.0x", "1.2x", "1.5x", "1.8x", "2.0x"];

  let playing = $state(true);
  let voiceIdx = $state(0);
  let speedIdx = $state(1);
</script>

<svelte:head>
  <title>tells - reader</title>
</svelte:head>

<div class="page">
  <nav class="mono">
    <div class="nav-left">
      <a href="#/library">back to library</a>
      <span class="doc-name">title-1.pdf</span>
    </div>
    <div class="nav-right">
      <span class="pos">p. 3 / 12</span>
      <ThemeToggle />
    </div>
  </nav>

  <main>
    <article>
      <h2 class="mono">Section 1</h2>
      <p class="dim">
        This text was generated by a language model. It exists so this page has something to read out loud. No human
        sat down and wrote it, which you can probably tell.
      </p>
      <p>
        {#each liveWords as word, i}<span class="live-word" style="animation-delay: {0.2 + i * 0.38}s">{word + " "}</span>{/each}
      </p>
      <p>
        Real documents will have real words in them. This one just needs enough text to fill a page and demonstrate
        the highlighting, so it keeps going for a while, saying very little.
      </p>
      <p class="last">
        If you have read this far, the demo has done its job. Thank you for listening to a computer describe itself.
      </p>
    </article>
  </main>

  <div class="player">
    <div class="generating mono">
      <span class="dot"></span>
      <span>generating p. 35-38 in background / local / cancel</span>
    </div>
    <div class="controls mono">
      <button class="play" onclick={() => (playing = !playing)}>{playing ? "||" : ">"}</button>
      <div class="timeline">
        <div class="track">
          <div class="progress"></div>
          <div class="cached" title="cached ahead"></div>
        </div>
        <div class="times"><span>04:12</span><span>31:40</span></div>
      </div>
      <div class="pills">
        <button title="Voice: click to change" onclick={() => (voiceIdx = (voiceIdx + 1) % voices.length)}>
          {voices[voiceIdx]}
        </button>
        <button title="Speed: click to change" onclick={() => (speedIdx = (speedIdx + 1) % speeds.length)}>
          {speeds[speedIdx]}
        </button>
      </div>
    </div>
  </div>
</div>

<style>
  @keyframes readhl {
    0%,
    0.9% {
      background-color: transparent;
    }
    1%,
    3.4% {
      background-color: var(--hl);
      color: var(--hl-ink);
    }
    3.5%,
    100% {
      background-color: transparent;
    }
  }

  .page {
    min-height: 100vh;
    background: var(--bg);
    color: var(--ink);
    display: flex;
    flex-direction: column;
  }

  nav {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 14px 24px;
    border-bottom: 1px solid var(--line);
    font-size: 13px;
  }

  .nav-left {
    display: flex;
    align-items: center;
    gap: 18px;
    min-width: 0;
  }

  .nav-left a {
    text-decoration: none;
    color: var(--muted);
    white-space: nowrap;
  }

  .doc-name {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .nav-right {
    display: flex;
    align-items: center;
    gap: 18px;
    white-space: nowrap;
  }

  .pos {
    color: var(--muted);
  }

  main {
    flex: 1;
    overflow-y: auto;
    padding: 56px 24px 160px;
  }

  article {
    max-width: 640px;
    margin: 0 auto;
    font-size: 20px;
    line-height: 1.85;
  }

  article h2 {
    font-size: 15px;
    font-weight: 500;
    color: var(--muted);
    letter-spacing: 0.08em;
    text-transform: uppercase;
    margin: 0 0 32px;
  }

  article p {
    margin: 0 0 24px;
  }

  article .dim {
    color: var(--muted);
  }

  article .last {
    margin: 0;
  }

  .live-word {
    animation: readhl 16s linear infinite;
    padding: 0 0.05em;
    margin: 0 -0.05em;
    border-radius: 2px;
  }

  .player {
    position: fixed;
    left: 0;
    right: 0;
    bottom: 0;
    border-top: 1px solid var(--line);
    background: var(--bg);
  }

  .generating {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 8px 24px;
    border-bottom: 1px solid var(--line);
    font-size: 12px;
    color: var(--muted);
  }

  .dot {
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background: var(--hl);
    display: inline-block;
  }

  .controls {
    max-width: 920px;
    margin: 0 auto;
    display: flex;
    align-items: center;
    gap: 18px;
    padding: 14px 24px;
    font-size: 13px;
  }

  .play {
    font: inherit;
    width: 44px;
    height: 44px;
    border-radius: 50%;
    border: 1px solid var(--ink);
    background: var(--ink);
    color: var(--bg);
    cursor: pointer;
    flex-shrink: 0;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .play:hover {
    background: var(--hl);
    color: var(--hl-ink);
    border-color: var(--hl);
  }

  .timeline {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 6px;
    min-width: 120px;
  }

  .track {
    height: 3px;
    background: var(--line);
    position: relative;
    border-radius: 2px;
    cursor: pointer;
  }

  .progress {
    position: absolute;
    left: 0;
    top: 0;
    height: 3px;
    width: 13%;
    background: var(--ink);
    border-radius: 2px;
  }

  .cached {
    position: absolute;
    left: 0;
    top: 0;
    height: 3px;
    width: 22%;
    background: var(--muted);
    opacity: 0.3;
    border-radius: 2px;
  }

  .times {
    display: flex;
    justify-content: space-between;
    color: var(--muted);
    font-size: 12px;
  }

  .pills {
    display: flex;
    align-items: center;
    gap: 10px;
    white-space: nowrap;
  }

  .pills button {
    font: inherit;
    font-size: 12.5px;
    background: var(--card);
    color: var(--ink);
    border: 1px solid var(--line);
    border-radius: 99px;
    padding: 8px 14px;
    cursor: pointer;
  }

  .pills button:hover {
    border-color: var(--ink);
  }
</style>
